#!/bin/sh
exec 2>&1
CFG=/etc/txtrader
USER=`cat $CFG/TXTRADER_DAEMON_USER`
VENV=`cat $CFG/TXTRADER_VENV`
. $VENV/bin/activate
exec envdir $CFG setuidgid $USER twistd --nodaemon --logfile=- --pidfile= --python=./rtx.tac

